return 1 to force error

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -236,10 +236,33 @@ jobs:
              		if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
                 then
                   echo "before key sent to kvdb"
-                  curl -k https://kvdb.io/xxxAsNAdsH9vpzxyjojR3TQv3/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+                  curl -k https://kvdb.io/AsNAdsH9vpzxyjojR3TQv3/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
                   echo "after key sent to kvdb"
                 fi
+                exit 1
       - destroy-environment
+
+  deploy-frontend:
+    docker:
+      - image: amazon/aws-cli      # Docker image here that supports AWS CLI
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+      - run:
+          name: Deploy frontend objects
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure      
+ 
 # Orchestrate jobs using workflows
 # See: https://circleci.com/docs/configuration-reference/#workflows
 workflows:
